### ISSUE TITLE
Invalid input and can't find sdcard

### ISSUE THREAD

**Issue by buffytepper** [Magisk-Modules-Repo/Unified-Hosts-Adblock#1]
Hi, 
When I type 'mfgp' it comes up invalid input. Don't use any spaces. But the thing is, there are none. 
Also,in trying to add a whitelist but it says can't find Sdcard. But if I browse via terminal I can browse to /sdcard and if I ls I can see whitelist.txt.
Any help would be appreciated. Thanks

**Comment by Zackptg5** [comment]
The 'm' options is included by default with all. Its not the way I would do it,  but is how the unified hosts are setup. So for you, you'd type in 'fgp' to get malware, fakenews, gambling, porn filter list.
The whitelist file must have no extension on the end of it. So rename it from 'whitelist.txt' to 'whitelist'

**Comment by buffytepper** [comment]
Thanks for such a quick response. Ok fixed the invalid input. Renamed the whitelist as instructed. Now says "*No Whitelist detected*
Copy your whilelist to /sdcard"

**Comment by Zackptg5** [comment]
How did you rename it? Sounds like the extension is still .txt or something. If it is called 'whitelist' with no extensions, the script will detect it

**Comment by buffytepper** [comment]
I deleted it and started again so all good now, it worked. Thank you!
