### ISSUE TITLE
UHA breaks some apps. (aka Magisk Hide? Per-app hosts file?)

### ISSUE THREAD

**Issue by nariox** [Magisk-Modules-Repo/Unified-Hosts-Adblock#2]
Hi, first of all, thank you for this great extension.
I'm currently running LineageOS on bacon (although that shouldn't matter, I think, but it might, see next paragraph) and trying to run VRV (funimation+crunchyroll app), but since the ads are blocked, it won't run.

I was wondering if Magisk Hide would allow the app to run (I can't test it since my device is stuck at Kernel 3.4, so Magisk Hide is unavailable for it)? This would be more convenient that disabling UHA systemwide everytime I needed to use VRV (or other similar apps).

Alternatively, would it be possible to use a per-app hosts file? I'm not too familiar with Android's way of sandboxing apps.

Thank you

**Comment by Zackptg5** [comment]
Magiskhide hides the su binary from the parts of Android system and apps of your choosing. So it basically hides root, not any of the modules. 
The hosts file affects the whole system so having that vary based on app isn't possible. Now there are some apps that block ads in specific apps by other mechanisms such as minminguard (but that's an Xposed framework module)

The best route of action for your case would be to determine which websites the app uses that are being blocked and whitelist them

**Comment by nariox** [comment]
Thanks for the suggestions.
